version: '3'

services:
  mwddevopsdemo_dev:
    container_name: mwddevopsdemo_dev
    image: cloudblueconnect/connect-extension-runner:25.0
    command: cextrun -d
    volumes: 
      - .:/extension
    env_file:
      - .mwddevopsdemo_dev.env

  mwddevopsdemo_bash:
    container_name: mwddevopsdemo_bash
    image: cloudblueconnect/connect-extension-runner:25.0
    working_dir: /extension
    command: /bin/bash
    stdin_open: true
    tty: true
    volumes:
      - .:/extension
    env_file:
      - .mwddevopsdemo_dev.env

  mwddevopsdemo_test:
    container_name: mwddevopsdemo_test
    image: cloudblueconnect/connect-extension-runner:25.0
    working_dir: /extension
    command: /bin/bash -c "poetry install && poetry run pytest"
    volumes:
      - .:/extension
    env_file:
      - .mwddevopsdemo_dev.env
